service: juanman-bot-spacex-takeoff

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1
  memorySize: 128
  timeout: 5
  endpointType: regional

  environment:
    BOT_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  mainbot:
    handler: handler.mainbot
    events:
      - http:
          path: webhook
          method: post
          cors: true
  set-webhook:
    handler: handler.setWebhook
    events:
      - http:
          path: setWebhook
          method: post
          cors: true

# resources:
#   Resources:
#     TakeoffSpaceXDynamoDbTable:
#       Type: 'AWS::DynamoDB::Table'
#       DeletionPolicy: Retain
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: chatid
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: chatid
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:provider.environment.DYNAMODB_TABLE}

resources:
  Resources:
    TakeoffSpaceXDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: SessionKey
            AttributeType: S
        KeySchema:
          - AttributeName: SessionKey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true